#!/bin/bash
# Quick start guide for Birthday Website

echo "🎂 Birthday Website - Quick Start Guide"
echo "========================================"
echo ""
echo "Step 1: Install dependencies"
echo "Run: pip install -r requirements.txt"
echo ""
echo "Step 2: Run the application"
echo "Run: python wish.py"
echo ""
echo "Step 3: Open in browser"
echo "Visit: http://localhost:5000"
echo ""
echo "📸 To add your photos:"
echo "1. Create a 'photos' folder"
echo "2. Add your images (jpg, png)"
echo "3. Update templates/index.html gallery section"
echo ""
echo "🎬 To add your videos:"
echo "1. Create a 'videos' folder"
echo "2. Add your videos (mp4)"
echo "3. Update templates/index.html videos section"
echo ""
echo "💌 To customize messages:"
echo "Edit wish.py and modify the messages list"
echo ""
echo "🎨 To change colors:"
echo "Edit static/style.css and update :root variables"
echo ""
echo "Happy Birthday! 💕🎉"
